import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const SFProDisplayRegular = localFont({
  src: "../../public/fonts/SF-Pro-Display-Regular.otf",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SFProDisplayRegular.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
